year: 2021
date: 2021-09-06
date_str: '2021-09-06'
camera: Senop
chemical_data: Vendemmia
calibration:
  source_folder: /home/user/data/raw/${db.date}/Senop/Vineyard Cattolica script_220901_203815/Vineyard Cattolica sequence
  target_folder: /home/user/data/interim/calibrated/${db.date}
  batch_size: 10
  geometric:
    distortion_1_name: /workspace/models/calibration/distortion_2021_1.txt
    distortion_2_name: /workspace/models/calibration/distortion_2021_2.txt
    intrinsic_matrix_1_name: /workspace/models/calibration/intrinsic_matrix_2021_1.txt
    intrinsic_matrix_2_name: /workspace/models/calibration/intrinsic_matrix_2021_2.txt
    selected_range_start: 1
    selected_range_stop: 53
    sensor_boundary: 21
  radiometric:
    name_hdr: /home/user/data/raw/2021-09-06/Senop_calibration/Vineyard Cattolica script_220901_203600/Vineyard Cattolica sequence/Vineyard Cattolica sequence_000006/Vineyard Cattolica sequence_000006.hdr
    name_dat: /home/user/data/raw/2021-09-06/Senop_calibration/Vineyard Cattolica script_220901_203600/Vineyard Cattolica sequence/Vineyard Cattolica sequence_000006/Vineyard Cattolica sequence_000006.dat
    second_hdr: /home/user/data/raw/2021-09-06/Senop_calibration/Vineyard Cattolica script_220901_204900/Vineyard Cattolica sequence/Vineyard Cattolica sequence_000005/Vineyard Cattolica sequence_000005.hdr
    second_dat: /home/user/data/raw/2021-09-06/Senop_calibration/Vineyard Cattolica script_220901_204900/Vineyard Cattolica sequence/Vineyard Cattolica sequence_000005/Vineyard Cattolica sequence_000005.dat
    wavelength_range_start: 0
    wavelength_range_stop: 53
    panel_config: [[311,711,311,711]]
    panel_vals: [[0.95]]
    dark_curr: null
    dark_curr_target: null
    calibration_time: null
    target_time: null
    year_bands: [500.0,508.2,510.0,516.3,524.5,532.7,540.8,549.0,556.5,557.1,565.3,573.5,581.6,589.8,598.0,600.0,606.1,614.3,622.4,630.6,638.8,646.9,655.1,663.3,671.4,679.6,687.8,695.9,704.1,712.2,720.4,728.6,736.7,744.9,753.1,761.2,769.4,777.6,785.7,793.9,802.0,810.2,818.4,826.5,834.7,842.9,851.0,859.2,867.3,875.5,883.7,891.8,900.0]
    sep_threshold_band: null
    sep_scaling: null
    sep_hdr: null
    sep_dat: null
    scale: 0.2
    threshold: true
    debug_folder: /home/user/data/interim/radiometric_plots/${db.date}
registration:
  general:
    source_folder: /home/user/data/interim/calibrated/${db.date}
    target_folder: /home/user/data/interim/registered/${db.date}
    batch_size: 10
    selected_range_start: 1
    selected_range_stop: 53
    false_RGB: [2,8,15]
  intensity:
    do_psr: true
    ref_band: 28
  sitk:
    do_sitk: false
    ref_band_sitk: 28
    max_shift: 200
    samples_per_axis: 10
    n_histogram_bins: 100
    convergence_window_size: 10
    convergence_min_value: 1.0e-6
    n_iterations: 100
segmentation:
  config_file: /workspace/src/segmentation/configs/wgisd_train_cfg.yaml
  weights_file: /workspace/models/segmentation/grape-152_final.pth
  source_folder: /home/user/data/interim/registered/${db.date}
  RGB_prefix: /false_RGB
  target_folder: /home/user/data/interim/segmented/${db.date}
  threshold: 0.99
  scale: 1
  apply_mask: true
  data_path: /workspace/src/segmentation/output/coco_instances_results.json
  annotation_path: /home/user/data/interim/segmented/${db.date}/annotations_pure
  annotation_CVAT: /home/user/data/interim/segmented/${db.date}/annotations_processed
  hypercubes_plots: true
  hypercubes_files: false
  false_RGB: [2,8,15]
  selected_range_start: 1
  selected_range_stop: 53
  chemical_file: /home/user/data/raw/lab_analyses/2021/redglobe_2021_lab_analyses.xlsx
  sheet_name: Vendemmia
  year_bands: [500.0,508.2,510.0,516.3,524.5,532.7,540.8,549.0,556.5,557.1,565.3,573.5,581.6,589.8,598.0,600.0,606.1,614.3,622.4,630.6,638.8,646.9,655.1,663.3,671.4,679.6,687.8,695.9,704.1,712.2,720.4,728.6,736.7,744.9,753.1,761.2,769.4,777.6,785.7,793.9,802.0,810.2,818.4,826.5,834.7,842.9,851.0,859.2,867.3,875.5,883.7,891.8,900.0]
  chem_ind: 7
  new_df_folder: /home/user/data/processed/${db.date}
  new_df_name: dataset
  excel_copy: true
  plot_spectra: true
  plot_batch_size: 7
  curve_start_ind: 5
  curve_end_ind: 12
  cleaning_debug: true
  cleaning_parameter: 2.2
prediction:
  analysis: bunches
  chemical_target: Brix
  inner_cv: 10
  outer_cv: 10
  max_comp: 15
  derivatives: [0,1,2]
  orders_start: 2
  orders_stop: 11
  wl_start: 2
  wl_stop: 16
  selected_range_start: 1
  selected_range_stop: 53
